/**
 * Created by Reid Beckett, Jun 12/2018
 */
public class C360_SponsorIndicatorsUtil {

    public static List<Account> findRelatedCustomerAccountsBySponsors(Set<Id> sponsorAccountIds){
        //TODO
        return null;
    }

    public static List<Account> findRelatedContactsBySponsors(Set<Id> sponsorAccountIds){
        //TODO
        return null;
    }

    public static List<Account> findRelatedCustomerAccounts(Set<Id> assetContactRoleIds){
        //TODO
        return null;
    }

    public static List<Account> findRelatedContacts(Set<Id> assetContactRoleIds){
        //TODO
        return null;
    }

    public static Map<Id, C360.SponsorIndicators> getSponsorIndicators(List<Account> customerAccounts){
        //TODO
        return null;
    }

    public static Map<Id, C360.SponsorIndicators> getSponsorIndicators(List<Contact> contacts){
        //TODO
        return null;
    }
}